# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XFIvrb0gM8VYwqyKMCdbGE_wATI1rgP1
"""

# -*- coding: utf-8 -*-

import streamlit as st
import requests
from anthropic import Anthropic

# ---------------- CONFIG ----------------
MONDAY_API_KEY = st.secrets["MONDAY_API_KEY"]
CLAUDE_API_KEY = st.secrets["CLAUDE_API_KEY"]

MONDAY_URL = "https://api.monday.com/v2"
BOARD_IDS = [5026839123, 5026839113]  # Work Order + Deal Funnel
# --------------------------------------

# Initialize Claude client
claude_client = Anthropic(api_key=CLAUDE_API_KEY)


def format_selected_boards(data):
    DEFAULTS = {
        "Status": "Pending",
        "Owner": "Unassigned",
        "Due Date": "No deadline",
        "Priority": "Normal",
        "Stage": "Early stage",
        "Deal Value": "Value not finalized"
    }

    text = ""

    for board in data["data"]["boards"]:
        text += f"\nBoard: {board['name']}\n"
        text += "-" * 40 + "\n"

        for item in board["items_page"]["items"]:
            text += f"Task: {item['name']}\n"

            for col in item["column_values"]:
                title = col["column"]["title"]
                value = col["text"]

                if value and value.strip():
                    text += f"{title}: {value}\n"
                elif title in DEFAULTS:
                    text += f"{title}: {DEFAULTS[title]}\n"

            text += "\n"

    return text


def fetch_latest_context():
    query = f"""
    {{
      boards(ids: {BOARD_IDS}) {{
        name
        items_page(limit: 50) {{
          items {{
            name
            column_values {{
              text
              column {{ title }}
            }}
          }}
        }}
      }}
    }}
    """

    headers = {
        "Authorization": MONDAY_API_KEY,
        "Content-Type": "application/json"
    }

    response = requests.post(
        MONDAY_URL,
        json={"query": query},
        headers=headers,
        timeout=30
    )

    return format_selected_boards(response.json())


def ask_chatbot(question, context):
    prompt = f"""
You are an assistant that answers questions using ONLY the data below.
Do not make assumptions beyond the data.

DATA:
{context}

QUESTION:
{question}

ANSWER:
"""

    response = claude_client.messages.create(
        model="claude-3-haiku-20240307",  # fast, cheap, reliable
        max_tokens=500,
        temperature=0.2,
        messages=[
            {"role": "user", "content": prompt}
        ]
    )

    return response.content[0].text


# ---------------- STREAMLIT UI ----------------
st.set_page_config(page_title="Monday AI Chatbot", layout="centered")

st.title("🤖 monday.com AI Chatbot (Claude)")
st.caption("Live data • Auto-updated • Board-aware")

question = st.text_input("Ask a question about work orders or deals:")

if question:
    with st.spinner("Fetching latest data..."):
        context_data = fetch_latest_context()

    with st.spinner("Thinking..."):
        answer = ask_chatbot(question, context_data)

    st.success("Answer")
    st.write(answer)
